spring:
  application:
    name: YourCarYourWay
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver